### ISSUE TITLE
Undefined variable: g:graphql_javascript_tags

### ISSUE THREAD

**Issue by chaucerbao** [sheerun/vim-polyglot#236]
When opening up a Javascript file, that error will be thrown.

```sh
Undefined variable: g:graphql_javascript_tags
```

https://github.com/sheerun/vim-polyglot/blob/master/after/syntax/javascript/graphql.vim#L13

**Comment by mcmillion** [comment]
Same thing here, started with commit 8b3418cab8eb5267b3a5743e4d5fe5f698d48bc8

**Comment by sheerun** [comment]
thanks for noticing, I've pushed a fix

**Comment by ShashankaNataraj** [comment]
Im still seeing this issue!

![image](https://user-images.githubusercontent.com/650317/39795403-81d54eb4-536d-11e8-9d82-2df5f7f02c3d.png)

**Comment by McKean** [comment]
Just encountered the same after an update today.

**Comment by squaresurf** [comment]
I just started getting this when opening typescript files.

More specifically this error when I open a typescript file:
```
Vim(execute):E121: Undefined variable: g:graphql_javascript_tags
```

**Comment by squaresurf** [comment]
I wouldn't mind it so much if I could find any documentation regarding what should set that variable to.

**Comment by jamestomasino** [comment]
This error just started getting thrown for me as well after an update to the latest.

**Comment by eidge** [comment]
Same here, reverting to the commit that fixed this issue initially fixes it for me.

Temporary workaround:

```
$ cd $VIM_DIR/bundle/vim-polyglot
$ git checkout 7673a61990d4062adebbe49f71067b0aad90382a
```

**Comment by sheerun** [comment]
This should be now fixed, please update

**Comment by squaresurf** [comment]
Thank you! It's fixed for me when opening typescript files :smile:.

**Comment by giulioroggero** [comment]
I have the same problem and I fixed it adding to .vimrc

`" disable graphql
let g:polyglot_disabled = ['graphql']`

**Comment by KevinBaileyCrum** [comment]
I know this is closed but I recently encountered the issue again.   Mine was in regards to v:true and v:false  Those are macros appearing in newer (mine is dated) versions of vim.  Simply set v:true to any non zero value and v:false to 0  https://github.com/vim-latex/vim-latex/issues/149

**Comment by ksrb** [comment]
@KevinBaileyCrum how did you manage to do set `v:true/false` as their internal vim variables isn't that impossible?

I tried:
```vimscript
let v:true = 1
let v:false = 0
```
But it didn't work 😞 .
