### ISSUE TITLE
Error on using <Tab>

### ISSUE THREAD

**Issue by meain** [sheerun/vim-polyglot#264]
I have both Supertab and Nvim-completion-manager

Steps to reproduce:

1) Open vim
2) Open a file ( it seems to happen in `ft=vim` buffer )
3) Type something, hit tab

Error Output:

```
Error detected while processing function LaTeXtoUnicode#omnifunc:
line   19:
E121: Undefined variable: b:l2u_last_compl
Press ENTER or type command to continue
Error detected while processing function LaTeXtoUnicode#omnifunc:
line   19:
E15: Invalid expression: col0 == b:l2u_last_compl['col0']
Press ENTER or type command to continue
Error detected while processing function LaTeXtoUnicode#omnifunc:
line   28:
E121: Undefined variable: b:l2u_last_compl
Press ENTER or type command to continue
Error detected while processing function LaTeXtoUnicode#omnifunc:
line   29:
E121: Undefined variable: b:l2u_last_compl
Press ENTER or type command to continue
Error detected while processing function LaTeXtoUnicode#omnifunc:
line   30:
E121: Undefined variable: b:l2u_last_compl
Press ENTER or type command to continue
Error detected while processing function LaTeXtoUnicode#omnifunc:
line   36:
E121: Undefined variable: s:l2u_esc_sequence
Press ENTER or type command to continue
Error detected while processing function LaTeXtoUnicode#omnifunc:
line   36:
E116: Invalid arguments for function feedkeys
Press ENTER or type command to continue
Error detected while processing function LaTeXtoUnicode#omnifunc:
line   19:
E121: Undefined variable: b:l2u_last_compl
Press ENTER or type command to continue
```

Disabling `julia` using `polyglot_disabled` gives me:
```
E117: Unknown function: LaTeXtoUnicode#Tab
E15: Invalid expression: LaTeXtoUnicode#Tab()
```

**Comment by sheerun** [comment]
this should be fixed when you update to newest version of polyglot, if not please reopen :)

**Comment by meain** [comment]
The issue is still present. Ping me if you need more information on this. @sheerun
