### ISSUE TITLE
wrong syntax highlighting of script tag on php file

### ISSUE THREAD

**Issue by Eduruiz** [sheerun/vim-polyglot#282]
So, I found it today after some testing.
There is a "test case":
![08-03-18--22 13 19](https://user-images.githubusercontent.com/1951631/37185032-21925f5e-231d-11e8-8377-361cb8e0bdf6.jpg)

Now with the plugin commented:
![08-03-18--22 15 31](https://user-images.githubusercontent.com/1951631/37185076-5876dafe-231d-11e8-9db0-e504a53438a0.jpg)

Note that on the second print I'm using StanAngeloff/php.vim without vim polyglot, so I'm creating the issue here.
`:set ft?` and `set syntax` both returns `php`, and seting `let g:polyglot_disabled = ['php']` don't solve the issue too.

I don't know how to investigate more or proceed from here.

**Comment by CH-DanReif** [comment]
Resolved by #294 ?

**Comment by Eduruiz** [comment]
@CH-DanReif seems so! :+1:
Thanks!!

**Comment by Eduruiz** [comment]
Ops! Ma bad.
It's still happening here, I just haven't reload the configs properly.
It happens on inline scripts with the `src` attribute too.

I can contribute with more information, just give me the directions. :)

**Comment by CH-DanReif** [comment]
@Eduruiz This should be an issue open on https://github.com/StanAngeloff/php.vim; we just use @StanAngeloff's syntax as-is.
