### ISSUE TITLE
Tons of errors if installed with fatih/vim-golang

### ISSUE THREAD

**Issue by DarrienG** [sheerun/vim-polyglot#357]
If installed at the same time as fatih/vim-go and a user tries to run `:GoInstallBinaries` it will throw a ton of errors and install none of the binaries.

Polyglot does not appear to have support for formatting or other features included in fatih/vim-go, which I'm sure is to minimize startup time, but at the same time is quite a pain, because it does not appear the two can be installed at the same time.

**Comment by rliebz** [comment]
I've run into a similar issue using [vim-plug](https://github.com/junegunn/vim-plug). I was able to get it working without any of those errors by plugging `vim-polyglot` after `vim-go`, although I'd call this a workaround rather than a fix.

Snippet from my vimrc:

```vim
call plug#begin('~/.vim/plugged')

" ...

Plug 'fatih/vim-go'
" polyglot can cause issues if not plugged last
Plug 'sheerun/vim-polyglot'
let g:polyglot_disabled = ['go']

call plug#end()
```

I'm not 100% if the change to `polyglot_disabled` is required or not.

**Comment by DarrienG** [comment]
I too am using vim-plug. It's not a solution I like, but I suppose it will do.

**Comment by sheerun** [comment]
I believe this is fixed now if you update vim-polyglot. If not, please comment

**Comment by meowgorithm** [comment]
I'm still experiencing this issue, even with `let g:polyglot_disabled = ['go']`. I'm using `vim-plug`.

**Comment by meowgorithm** [comment]
Disregard, running the build script fixed things. With [vim-plug][plug] this was a matter of:

    Plug 'sheered/vim-polyglot', { 'do' : './build' }`

[plug]: https://github.com/junegunn/vim-plug

**Comment by sheerun** [comment]
I've updated vim-polyglot so it should work without build now

**Comment by meowgorithm** [comment]
Ah, interesting. I'm still getting tons of errors with NeoVim.

**Comment by sheerun** [comment]
strange. build should not change anything. maybe you can send what is changed in vim-polyglot folder after you run `./build`? Please make sure you update vim-polyglot to newest version before you run it

**Comment by meowgorithm** [comment]
Link below. What does `./build` do exactly?

https://www.dropbox.com/s/lofo84aq34nflvk/vim-polyglot.zip?dl=0

**Comment by sheerun** [comment]
There seems to be no difference
