### ISSUE TITLE
vim-rego unconditionally sets comments and commentstring

### ISSUE THREAD

**Issue by anowlcalledjosh** [sheerun/vim-polyglot#415]
This has been included verbatim into `polyglot.vim`:

```vim
autocmd BufRead,BufNewFile *.rego set filetype=rego

" Use # as a comment prefix
setlocal comments=b:#,fb:-
setlocal commentstring=#\ %s
```

which has the result that `comments` and `commentstring` are unconditionally set incorrectly.

This is broken since #406.

**Comment by sheerun** [comment]
I'm removing rego syntax until this is fixed

**Comment by sheerun** [comment]
(please contribute to upstream repository)

**Comment by Okonos** [comment]
The issue with `vim-rego` seems to have been fixed, see https://github.com/tsandall/vim-rego/pull/8/commits/cc8a057fa825f7c813187b293eeb48091c8f4983

Would you mind reintroducing the support for the plugin?

**Comment by sheerun** [comment]
@Okonos It wasn't fixed properly. `comment` commands should go to `ftplugin/rego.vim`, please see any other filetype plugin. vim-polyglot completely skips loading ftdetect directory (it generates its own), so it won't work
