### ISSUE TITLE
g:polyglot_disabled = ['autoindent'] doesn't allow vim-sleuth to load

### ISSUE THREAD

**Issue by andrey-bolduzev** [sheerun/vim-polyglot#541]
**Does this bug happen when you install plugin without vim-polyglot?**
No

**Describe the bug:**
For reasons unrelated to this bug I would like to disable the polyglot version of the indent detection and continue using vim-sleuth. Now, I can only speculate, but I assume, by default, vim-polyglot somehow detects that vim-sleuth is loaded and unloads it, since no vim-sleuth commands are available starting from vim-polyglot v4.8.0?

Is it possible to make it so `g:polyglot_disabled = ['autoindent']` also lets vim-sleuth be loaded normally?

**To Reproduce:**
- Have vim-sleuth and vim-polyglot (version v4.8.0+) installed.
- Have `g:polyglot_disabled = ['autoindent']` applied
- Verify `:Sleuth` is not found

**Comment by sheerun** [comment]
I've fixed disabling of autoindent. Do you mind to tell why you prefer Sleuth?

**Comment by andrey-bolduzev** [comment]
Hmm, it's possible I'm doing something wrong but on the latest version I'm still not seeing vim-sleuth commands being available with `g:polyglot_disabled = ['autoindent']`. Everything works with v4.7.1.

Regarding the reasons:
1. On the latest vim-polyglot version as of yesterday I was working with some Kotlin files and something strange was happening with the suggested indent being a mix of tabs and spaces, which was drastically different from how vim-sleuth used to see it.
2. Not sure if it's possible with the embedded solution, but I like how I can use the provided `SleuthIndicator` function in my lightline.

![image](https://user-images.githubusercontent.com/32677949/92608879-e08a0280-f283-11ea-86b7-c69d918d8b29.png)

**Comment by sheerun** [comment]
Thank you for answer

ad 1. Could you send this file? The goal is to work exactly the same as Sleuth, but with superior performance

ad2. I've re-introduced SleuthIndicator function so you can use it with vim-polyglot

**Comment by sheerun** [comment]
Also, I've double-checked `g:polyglot_disabled = ['autoindent']` should work now

**Comment by andrey-bolduzev** [comment]
I might be misunderstanding something but I don't see the latest version of vim-polyglot with `g:polyglot_disabled = ['autoindent']` falling back to vim-sleuth detection. E.g., the lightline indicator is back (which is great for debugging) but it's clearly backed by the new logic instead of vim-sleuth.

I'm observing the unexpected indent detection in a project I cannot quite share and I cannot reproduce the issue with other more basic projects I have at hand or the same file from the project but put in a directory outside of the project (in which case the indent is detected correctly).

I wonder if it's possible to enable verbose messaging behind another flag to figure out where the detected indent is coming from. As far as I can see, there isn't a file that uses 3 spaces for indentation but is what vim-polyglot detects where vim-sleuth sees expected tab indentation.

**Comment by sheerun** [comment]
Do you have `g:polyglot_disabled` at the top of .vimrc?

**Comment by sheerun** [comment]
I'd gladly fix indentation detection but I'd need some file to reproduce. Probably some line in this file has 3 spaces indentation

**Comment by sheerun** [comment]
if you update vim-polyglot you can run `:echo b:sleuth_culprit` to how line that caused indentation to be changed

**Comment by andrey-bolduzev** [comment]
> Do you have `g:polyglot_disabled` at the top of .vimrc?

Nope, I had it with the rest of the config. I see now it works if I put it before `call plug#begin('~/.vim/plugged')` but my understanding is this would be a bit unusual?

> I'd gladly fix indentation detection but I'd need some file to reproduce. Probably some line in this file has 3 spaces indentation

This specific file definitely doesn't have the 3-space indentation anywhere (which is why it's detected correctly when the file is ripped out of the surrounding project, I speculate).

> if you update vim-polyglot you can run `:echo b:sleuth_culprit` to show line that caused indentation to be changed

Thanks! In the latest observations, inside one of the "bad" files `:echo b:sleuth_culprit` prints out a path to the first file it can discover I think (the file is called `Add....kt`). And inside the "cuprit" file, the new culprit is just `kotlin`.

**Comment by sheerun** [comment]
`b:sleuth_culprit` should have format `FILENAME:LINECONTENTS`, but I've just changed it to `FILENAME:LINE_NUMBER` so it's more readable. If you try this again you should get exact file and line that causes it

**Comment by sheerun** [comment]
(if you update)

**Comment by sheerun** [comment]
> Nope, I had it with the rest of the config. I see now it works if I put it before call plug#begin('~/.vim/plugged') but my understanding is this would be a bit unusual?

Current implementation loads all plugins just once when vim-polyglot is loaded and it uses `g:polyglot_disabled` to tell whether to load them or not. Setting `g:polyglot_disabled` anytime during runtime will be supported, but I need to import all filetypes from upsteam vim runtime, which can take few months...

**Comment by andrey-bolduzev** [comment]
Hmm, I'm on https://github.com/sheerun/vim-polyglot/commit/2dc954d6fa15c897da59ff14aa4d5991a3329eb5 and, strangely, I don't see the line number. I wonder if it doesn't go into that if-branch.

**Comment by sheerun** [comment]
you need to remove `g:polyglot_disabled = ['autoindent']` if you have it

**Comment by andrey-bolduzev** [comment]
> you need to remove `g:polyglot_disabled = ['autoindent']` if you have it

I'm afraid that was with a clean config, no polyglot customization.

**Comment by sheerun** [comment]
I think it's because it detected tabs (I've pushed fix for `b:sleuth_culprit`). I think I know what's going on. When tabs are detected vim-polyglot just runs `setlocal noexpandtab` and doesn't change shiftwidth or tabstop settings (it's so you can set them by yourself in .vimrc). I guess we need to set some of them to fixed values when tabs are detected (which ones?)

**Comment by andrey-bolduzev** [comment]
Ah, yes, I see it points to the first tab-indented line in the first file now.

Not sure about the specific values but if it's useful at all, for comparison, in the culprit file:
- vim-polyglot: `sw=3,ts=4`,
- vim-sleuth: `ts=4`.

This is all without any global Kotlin overrides.

**Comment by sheerun** [comment]
@andrey-bolduzev Thanks for this info. I'm pretty sure this should be fixed now (vim-polyglot now sets ts = sw if they are different, and tabs are used, just like sleuth).

**Comment by sheerun** [comment]
whoops, there was debugging code left. I've removed it

**Comment by andrey-bolduzev** [comment]
Fantastic, thank you very much for your work!

**Comment by sheerun** [comment]
btw. you can use sleuth if you want but vim-polyglot version is much faster for various reasons, and you can set tabstop to your liking in .vimrc (instead of default 8)
