### ISSUE TITLE
Polyglot is wrongly setting tabstop to 2 on several file types

### ISSUE THREAD

**Issue by ianliu** [sheerun/vim-polyglot#648]
**Does this bug happen when you install plugin without vim-polyglot?**
Don't know, because this happens on several file types, so I cannot pinpoint a single plugin. It also happens on files *without* a file type.

**Describe the bug:**
When Polyglot is enabled, `tabstop` is set to 2 on at least these files:

 * Makefiles
 * Text files
 * C/C++
 * Files without a type

On C/C++ is specially troublesome because shiftwidth is still 8, thus vim is adding 4 tab characters on every indentation level.

**To Reproduce:**
Enable Polyglot master (73c5187) and open vim. Now inspect the value of `tabstop` with `set ts?`.

**Comment by enzo-sa** [comment]
the default tabstop was set to 2 with commit [29ec69ffa095a16fe15e4c63c1a6ba90974efd74](https://github.com/sheerun/vim-polyglot/commit/29ec69ffa095a16fe15e4c63c1a6ba90974efd74)
deleting the code there that changes the tabstop to 2 fixes this for me

**Comment by ianliu** [comment]
I've managed to circumvent the issue by setting `let g:polyglot_disabled = ["autoindent"]` before polyglot is loaded. Nonetheless, I think the default behavior is wrong and should be fixed; I don't really understand the purpose of the commit 29ec69f.

**Comment by sheerun** [comment]
Shiftwidth should be also set to 2 which should fix this issue. If you really like 8 tabs indent you can use `let g:polyglot_disabled = ["autoindent"]`. If you wish to use custom tabstop, just write something like `set ts=4` at the top of .vimrc (before vim-polyglot is loaded)

**Comment by shtrom** [comment]
The problem is still present. I found it as it messed up the indentation of files when seen on different systems. I don't think unconditionally changing such a default without a very specific configuration option to not do it is a good idea \:

**Comment by rch77** [comment]
The problem is still present. Disabling "autoindent" or "sensible" creates other problems, like syntax not fully loaded for .blade.php, i.e. % key doesn't jump as it should on @if. Or Visual line not changing background if you have :set bg=dark
I don't think it is sensible to change tabstop=8 ever. It makes source unreadable without special tab decoding and can't work for anything but one-person projects. Even then you can't read it without any other editor/viewer.
And all I wanted just quick syntax highlighting for .blade.php.

~/.vimrc
```
set noexpandtab tabstop=8 shiftwidth=4 softtabstop=4 background=dark ignorecase textwidth=0 nocompatible modeline
set backup backupdir=~/tmp
set encoding=utf-8
set undofile updatecount=50 history=1000
" to prevent polyglog messing up with tabstop
"let g:polyglot_disabled = ["sensible"]
call plug#begin()
" The default plugin directory will be as follows:
"   - Vim (Linux/macOS): '~/.vim/plugged'
"   - Vim (Windows): '~/vimfiles/plugged'
Plug 'sheerun/vim-polyglot'
"
" Initialize plugin system
call plug#end()
set noexpandtab tabstop=8 shiftwidth=4 softtabstop=4 ignorecase textwidth=0 nocompatible modeline

```

**Comment by overbyte** [comment]
Not sure why this was closed - it's rendered vim-polyglot unusable for me

**Comment by socherbyc** [comment]
Still an issue. Polyglot is unusable for languages that use 4 spaces :/
