### ISSUE TITLE
"E325: ATTENTION" does not appear when a swapfile exists

### ISSUE THREAD

**Issue by cwfoo** [sheerun/vim-polyglot#672]
**Does this bug happen when you install plugin without vim-polyglot?**

Not applicable because the problem is with vim-polyglot itself (`ftdetect/polyglot.vim`).

**Describe the bug:**

When opening a file that has a swapfile,  `E325: ATTENTION` will not be shown.

This bug was introduced in v4.16.0 in commit 739102e06df4fe5bca752d1163b954603912bc98.

**To Reproduce:**

1. Add `set swapfile` to your Vim configuration file.
2. Open a new file in Vim (e.g. `test.py`) and save it. Do not close Vim.
3. Open the file from step (2) in another instance of Vim.

Observation: `E325: ATTENTION` does not appear in step (3).

Expected behavior: `E325: ATTENTION` appears.

Please make this behavior optional.

**Comment by kronion** [comment]
Related to #638. The `noswapfile` change was reverted, but vim still does not prompt the user when a swapfile already exists. Instead, it starts a new swapfile, eg. `[filename].swo`. This means that the preexisting swapfile (`[filename].swp`) sits around unused and forgotten about.

It's possible to manually recover the existing swapfile with `:recover`, but I doubt many vimmers know to do this, especially if they never had to before. This plugin changes the behavior on them silently.

**Comment by jaawerth** [comment]
If this is left as the default, I'd at least strongly request that it be documented somewhere prominent in the README, if not print a warning upon install/upgrade; `set shortmess+=A` changes an important assumption about a core (n)vim behavior, and it isn't something one would expect a plugin that manages syntax files to change without warning the user.

I myself finally got to the point where I grepped my entire `~/.config/nvim` directory for it to figure out which plugin was letting me open the same file in two different instances without warning me unless I attempt to save one after changing it from the other.

**Comment by cwfoo** [comment]
For those who want to avoid this problem, and who don't mind running an older version of vim-polyglot from October 2020:

```
git checkout f52f6b95
# Or equivalently:
git checkout v4.16.0~1
```

**Comment by Farzat07** [comment]
```let g:polyglot_disabled = ['sensible']``` should solve the problem.

**Comment by smemsh** [comment]
I am not sure what is the relation to `vim-sensible`? This does not fix the problem and I don't see `shortmess` anywhere in sensible plugin, what am I missing?

The problem is [here in init.py from autoload]( https://github.com/sheerun/vim-polyglot/blob/730dcb02caab60a6ae5d8b4bdc16d290041061ec/autoload/polyglot/init.vim#L2731) introduced in commit 05b8bbc93 and seems to come from #613.  The comment is:

> This is needed to avoid swapfile warning when auto-reloading

but seems to ignore that the swapfile warning is used in many other contexts.

If polyglot is starting to go around changing random global settings this is sure to cause problems; what one person thinks is no big deal, another will find disastrous.  In no way should polyglot be changing global settings like this, which break core vim assumptions.  It's for syntax highlighting.

This commit brazenly changes `shortmess`, this is nuts.  People have vim settings for a reason.  Not quite as crazy as disabling swap files but it's up there...

**Comment by smemsh** [comment]
ok, now I see that the shortmess code is protected under
```
if !has_key(g:polyglot_is_disabled, 'sensible')
```
trying this in polyglot_is_disabled did not work for me because it was getting overwritten later in my config.  I can confirm it does work when disabling it correctly.  I suppose that makes it better but this is certainly surprising and I don't think it should be the default.  It's written in the main project README that it uses vim-sensible, but that never caused issues before and I wouldn't dream it would be messing with these kinds of settings (I don't see anything with `shortmess` in tpope's vim-sensible either).

I did overwrite files which had other editing sessions because of this, which is what led me here.  I do rely on vim to tell me if a new edit is actually somewhere else.  I imagine many people do.  I also think people wouldn't necessarily want to disable all of `sensible` just to get their `shortmess` sane.

**Comment by ZeroKnight** [comment]
I found this issue when I realized my `swapfile` setting was disabled and `A` mysteriously wound up in my `shortmess`...

Why is "sensible" even part of this plugin, let alone *enabled by default*? Setting things like `noswapfile` and `shortmess+=A` globally is well beyond the scope of a **filetype plugin**; users can make these choices on their own. Why is [vim-sleuth](https://github.com/tpope/vim-sleuth) bundled in this plugin? If users wanted sleuth, they should just install sleuth...

I appreciate the time and effort into assembling so many filetype plugins into a single collection. However, these inclusions are unnecessary bloat at best, and at worst duplicate and possibly conflict with user settings and/or the plugins being emulated here. Please consider removing them, or at the *very least* leave them disabled by default. This frankly a very puzzling and out-of-place addition with surprising behavior.

**Comment by sheerun** [comment]
`A` means: `don't give the "ATTENTION" message when an existing swap file is found`. Setting it or not doesn't matter if `swapfile` is disabled by user. Vim-polyglot sets **defaults** for some settings that are relevant for good language support. Disabling this message is necessary for auto-reloading of buffers if multiple vim windows are used, otherwise you'd need to confirm warning in each of the windows.

**Comment by sheerun** [comment]
> Related to #638. The noswapfile change was reverted, but vim still does not prompt the user when a swapfile already exists. Instead, it starts a new swapfile, eg. [filename].swo. This means that the preexisting swapfile ([filename].swp) sits around unused and forgotten about.

It's automatically removed when vim closes, unless someone exited vim in crashing fashion, like closing terminal window instead of exiting Vim first. In this case swapfiles being left on the disk is proper behavior to prevent potential losses.

> It's possible to manually recover the existing swapfile with :recover, but I doubt many vimmers know to do this, especially if they never had to before. This plugin changes the behavior on them silently.

If they want to recover something, they will for sure google for "vim recover file" which explains this command.

**Comment by ZeroKnight** [comment]
> `A` means: `don't give the "ATTENTION" message when an existing swap file is found`. Setting it or not doesn't matter if `swapfile` is disabled by user.

Sorry, I'll have to retract that part; I misread my grep output and conflated unrelated `setl noswapfile` lines for scratch buffers with the `sensible` section. I didn't catch it at first because I was checking `set swapfile?` at the vim-startify splash screen, which locally sets `noswapfile` (I should have checked in an empty buffer). Kindly disregard.

> Disabling this message is necessary for auto-reloading of buffers if multiple vim windows are used, otherwise you'd need to confirm warning in each of the windows.

The "Attention" prompt would only be shown in windows with modified buffers; unmodified ones would still reload without the prompt, which I think is a reasonable warning. I see the value in disabling the message and just using `:recover` when needed, but I don't agree that it should be the default.

**Comment by sheerun** [comment]
> The "Attention" prompt would only be shown in windows with modified buffers

All buffers can be modified e.g. when you checkout a commit, then you need to manually "unblock" all instances by confirming ATTENTION message in each of the windows individually

**Comment by bb010g** [comment]
> Disabling this message is necessary for auto-reloading of buffers if multiple vim windows are used, otherwise you'd need to confirm warning in each of the windows.

https://github.com/chrisbra/Recover.vim handles this case without disrupting normal swapfile usage. Adding `A` to 'shortmess' stops any autocommands for the `SwapExists` event from working, as neither `vim -r` nor `:recover` trigger the `SwapExists` event.
